### ISSUE TITLE
No update from F-Droid?

### ISSUE THREAD

**Issue by ivysrono** [rsteube/t4-launcher#15]
Still 1.0, no build log.

**Comment by rsteube** [comment]
Yeah keep wondering myself, it does take some time occasionally but it seems there is something wrong with the [configuration](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.github.rsteube.t4.yml).

**Comment by rsteube** [comment]
https://f-droid.org/wiki/index.php?title=com.github.rsteube.t4/lastbuild_1&redirect=no
