### ISSUE TITLE
Hide buttons

### ISSUE THREAD

**Issue by Donkey-Doug** [rsteube/t4-launcher#18]
Make it possible to hide the shortcut buttons.

**Comment by rsteube** [comment]
The shortcut buttons are the central purpose of this launcher so i don't see much sense in it to hide them.
The idea behind this is to have a somewhat spotlight/dmenu experience which trains your muscle memory.
[minimalist-launcher](https://github.com/Collinux/minimalist-launcher) doesn't have buttons if a simple list is desired.
