### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [rsteube/t4-launcher#3]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by rsteube** [comment]
There should be one, is it perhaps not loading? https://f-droid.org/en/packages/com.github.rsteube.t4/

**Comment by mondlicht-und-sterne** [comment]
oh it works now thanks for asking
