### ISSUE TITLE
feature request: support Number and Symbols

### ISSUE THREAD

**Issue by ivysrono** [rsteube/t4-launcher#7]
https://github.com/k9mail/k-9

`9` and `-`.

Maybe T9 is better than T4.

**Comment by rsteube** [comment]
Seems numbers were still missing. Any non-word characters as well as numbers and underscore are implicit.
So for `K-9 Mail` just match `KMail` (or `Mail` which already works).
T9 is good for typing text, this is intentionally reduced to enable quick filtering (strongly opiniated of course, but 4 buttons seemed quite alright after getting accustomed to it).
